=== AtayDev/XSD-Validation/XSD Validation/annuaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="annuaire">
        <xs:complexType>
            <xs:sequence>
             <xs:element name="personne" maxOccurs="unbounded">
                 <xs:complexType>
                     <xs:sequence>
                         <xs:element name="nom" type="xs:string"/>
                         <xs:element name="prenom" type="xs:string"/>
                         <xs:element name="telephone">
                             <xs:simpleType>
                                 <xs:restriction base="xs:string">
                                     <xs:pattern value="0(5|6|7|8|9)[0-9]{8}"/>
                                 </xs:restriction>
                             </xs:simpleType>
                         </xs:element>
                         <xs:element name="email">
                             <xs:simpleType>
                                 <xs:restriction base="xs:string">
                                     <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                 </xs:restriction>
                             </xs:simpleType>
                         </xs:element>
                         <xs:element name="sexe">
                             <xs:simpleType>
                                 <xs:restriction base="xs:string">
                                     <xs:pattern value="M|F"/>
                                 </xs:restriction>
                             </xs:simpleType>
                         </xs:element>
                         <xs:element name="DateNaissance" type="xs:date"/>
                         <xs:element name="adresse">
                             <xs:complexType>
                                 <xs:sequence>
                                     <xs:element name="rue">
                                         <xs:complexType>
                                             <xs:simpleContent>
                                                 <xs:extension base="xs:string">
                                                     <xs:attribute name="numero" type="xs:integer"/>
                                                 </xs:extension>
                                             </xs:simpleContent>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="ville" type="xs:string">
                                         
                                     </xs:element>
                                     
                                 </xs:sequence>
                             </xs:complexType>
                         </xs:element>
                         
                     </xs:sequence>
                     <xs:attribute name="matricule" type="xs:ID"/>
                     <xs:attribute name="nationalite">
                         <xs:simpleType>
                             <xs:restriction base="xs:string">
                                 <xs:length value="3"/>   
                             </xs:restriction>
                         </xs:simpleType>
                     </xs:attribute>
                     
                 </xs:complexType>
             </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AtayDev/XSD-Validation/XSD Validation/annuaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<annuaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="annuaire.xsd">
    <personne matricule="AB123">
        <nom>Alami</nom>
        <prenom>Wafae</prenom>
        <telephone>0661112233</telephone>
        <email>alami@ensias.ma</email>
        <sexe>F</sexe>
        <DateNaissance>1980-10-10</DateNaissance>
        <adresse> 
            <rue numero="12">Sebta </rue>
            <ville>Rabat</ville> 
        </adresse> 
    </personne>
    <personne matricule ="XZ123" nationalite="FRA">
        <nom>Alaoui</nom>
        <prenom>Adam</prenom>
        <telephone>0674152638</telephone>
        <email>adam_alaoui@ensias.ma</email>
        <sexe>M</sexe>
        <DateNaissance>1970-11-10</DateNaissance>
        <adresse> 
            <rue numero="12">Sebta</rue>
            <ville>Casablanca</ville> 
        </adresse>
    </personne>
</annuaire>
